/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GSON;
import com.google.gson.Gson;

import java.io.*;
import java.util.Random;

public class Quotes {

    public static void main(String[] args) throws IOException {

            InputStream inputStream = Quotes.class.getResourceAsStream("/recentquotes.json");
            InputStreamReader reader = new InputStreamReader(inputStream);

            Gson gson = new Gson();
            Quote[] quotesAndAuthorArray = gson.fromJson(reader, Quote[].class);

            Random random = new Random();
            int randomNumber = random.nextInt(quotesAndAuthorArray.length);
            System.out.println(quotesAndAuthorArray[randomNumber].toString());

//            quotesAndAuthor[] quotesAndAuthorsArray = gson.fromJson(jsonFileReader, quotesAndAuthor[].class);


    }


    }


